MediLink/Entities/Practitioner.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MediLink.Entities
{
    public class Practitioner
    {
        public int Id { get; set; }

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 100)]
		public string Password { get; set; } = null!;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 100)]
		public string Email { get; set; } = null!;

        public bool IsValidated { get; set; }

        public bool passwordReset { get; set; } = false;

        public string token { get; set; } = string.Empty;

        public bool IsDeleted { get; set; } = false;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 250)]
		public string FirstName { get; set; } = null!;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 250)]
		public string LastName { get; set; } = null!;

		public string? gender { get; set; }

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 12)]
		public string PhoneNumber { get; set; } = null!;

        public DateTime? lastPatientAcceptedDate { get; set; }

        public bool IsAcceptingNewPatients { get; set; }

        public ICollection<PractitionerSpokenLanguages> PractitionerSpokenLanguages { get; set; }
				
		public ICollection<PractitionerOfficeAddress> PractitionerAddress { get; set; }

        public ICollection<NewPatientRequest>? NewPatientRequests { get; set; }

        public ICollection<PractitionerPatient>? PractitionerPatients { get; set; }

        public ICollection<PractitionerReview>? PractitionerReviews { get; set; }

        public ICollection<WaitList>? WaitLists { get; set; }

        public int PractitionerTypeId { get; set; }

		public PractitionerType PractitionerType { get; set; } = null!;

        public double? rating { get; set; }

    }
}

MediLink/Entities/PractitionerType.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MediLink.Entities
{
    public class PractitionerType
    {
        public int Id { get; set; }

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 250)]
		public string Name { get; set; } = null!;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 350)]
		public string Description { get; set; } = null!;

        public bool IsDeleted { get; set; } = false;

        public ICollection<Practitioner>? Practitioners { get; set; }
    }
}

MediLink/Models/PractitionerViewModel.cs
using MediLink.Entities;

namespace MediLink.Models
{
    public class PractitionerViewModel
    {
        public Practitioner Practitioner { get; set; }

        public List<OfficeAddress> OfficeAddresses { get; set; }

        public List<PractitionerSpokenLanguages> PractitionerSpokenLanguages { get; set; }

        public PractitionerType PractitionerType { get; set; }

        public string IsAcceptingNewPatients { get; set; }

        public string LastAcceptedPatientDate { get; set; }

    }
}

MediLink/Controllers/PractitionerController.cs
using MediLink.Entities;
using MediLink.Models;
using MediLink.Services;
using MediLink.Services.Contract;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.IO;
using System.Security.Claims;
using System.Text.RegularExpressions;

namespace MediLink.Controllers
{
    public class PractitionerController : Controller
    {
        public PractitionerController(MediLinkDbContext mediLinkContext, IUserService userService, IWebHostEnvironment webHostEnvironment)
        {
            _mediLinkContext = mediLinkContext;
            _userService = userService;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> PractitionerHomePage()
        {
            //created by juan quintana -setup a message to inforn status for add or remove address
            string mensajeResultSave = TempData["mensajeResultSaveAddress"] as string;
        
            ViewData["messageUpdatePract"] = mensajeResultSave;

            //created by juan quintana -setup a message to inforn status for add or remove address
            string mensajeResAddAddress = TempData["mensajeResultAddAddress"] as string;

            ViewData["messageUpdateOffic"] = mensajeResAddAddress;



            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["userName"] = userName;

            Practitioner practitioner = await _userService.GetPractitionerByEmail(userName);

            List<PractitionerOfficeAddress> practitionerOfficeAddresses = await _mediLinkContext.PractitionerAddresses
                .Where(pa => pa.PractitionerId == practitioner.Id)
                .Include(pa => pa.OfficeAddresses)
                .ThenInclude(oa => oa.OfficeType)
                .ToListAsync();

            List<OfficeAddress> officeAddresses = new List<OfficeAddress>();

            foreach(var officeAddress in practitionerOfficeAddresses)
            {
                officeAddresses.Add(officeAddress.OfficeAddresses);
            }

            List<PractitionerSpokenLanguages> practitionerSpokenLanguages = await _mediLinkContext.PractitionerSpokenLanguages
                .Where(psl => psl.PractitionerId == practitioner.Id).Include(psl => psl.Language).ToListAsync();

            PractitionerType practitionerType = await _mediLinkContext.PractitionerTypes
                .Where(pt => pt.Id == practitioner.PractitionerTypeId)
                .FirstOrDefaultAsync();

            string isAcceptingNewPatients = ""; 
            if (practitioner.IsAcceptingNewPatients == true) 
            {
                isAcceptingNewPatients = "Currently accepting new patients";
            }
            else 
            {
                isAcceptingNewPatients = "Currently not accepting new patients";
            }

            string lastAcceptedPatientDateString = practitioner.lastPatientAcceptedDate.ToString();

            if (!string.IsNullOrEmpty(lastAcceptedPatientDateString) || !string.IsNullOrWhiteSpace(lastAcceptedPatientDateString))
            {
                lastAcceptedPatientDateString = practitioner.lastPatientAcceptedDate.ToString().Substring(0, 11);
            }
            else
            {
                lastAcceptedPatientDateString = "No patients accepted yet";
            }

            var reviews = await _mediLinkContext.PractitionerReviews.Where(pr => pr.PractitionerId == practitioner.Id).ToListAsync();
            if(reviews.Count > 0)
            {
                double rating = reviews.Average(r => r.Rating);
                practitioner.rating = rating;
            }
            else
            {
                practitioner.rating = 0;
            }


            PractitionerViewModel practitionerViewModel = new PractitionerViewModel()
            {
                Practitioner = practitioner,
                OfficeAddresses = officeAddresses,
                PractitionerSpokenLanguages = practitionerSpokenLanguages,
                PractitionerType = practitionerType,
                IsAcceptingNewPatients = isAcceptingNewPatients,
                LastAcceptedPatientDate = lastAcceptedPatientDateString
            };

            return View(practitionerViewModel);
           
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePractitionerDetails()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["userName"] = userName;

            Practitioner practitioner = await _userService.GetPractitionerByEmail(userName);

            PractitionerType currentPractitionerType = await _mediLinkContext.PractitionerTypes
                .Where(pt => pt.Id == practitioner.PractitionerTypeId)
                .FirstOrDefaultAsync();

            List<PractitionerSpokenLanguages> practitionerSpokenLanguages = await _mediLinkContext.PractitionerSpokenLanguages
                .Where(psl => psl.PractitionerId == practitioner.Id)
                .ToListAsync();

            List<int> currentSpokenLanguageIds = new List<int>();

            foreach (var language in practitionerSpokenLanguages)
            {
                currentSpokenLanguageIds.Add(language.LanguageId);
            }

            List<PractitionerType> practitionerTypes = await _mediLinkContext.PractitionerTypes.ToListAsync();

            List<Languages> languages = await _mediLinkContext.Languages.ToListAsync();

            string isAcceptingNewPatients = "";
            if (practitioner.IsAcceptingNewPatients = true)
            {
                isAcceptingNewPatients = "true";
            }
            else
            {
                isAcceptingNewPatients = "false";
            }

            PractitionerUpdateViewModel practitionerUpdateViewModel = new PractitionerUpdateViewModel()
            {
                Email = practitioner.Email,
                FirstName = practitioner.FirstName,
                LastName = practitioner.LastName,
                Gender = practitioner.gender,
                PhoneNumber = practitioner.PhoneNumber,
                IsAcceptingNewPatients = isAcceptingNewPatients,
                Languages = languages,
                CurrentSpokenLanguageIds = currentSpokenLanguageIds,
                PractitionerTypes = practitionerTypes,
                CurrentPractitionerTypeId = currentPractitionerType.Id

    };

            return View(practitionerUpdateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePractitionerDetails(PractitionerUpdateViewModel practitionerUpdateViewModel)
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            List<string> errorMessage = new List<string>();
            string phonePattern = @"^\d{3}-\d{3}-\d{4}$";
            Regex regex = new Regex(phonePattern);

            if (string.IsNullOrEmpty(practitionerUpdateViewModel.Email) || string.IsNullOrWhiteSpace(practitionerUpdateViewModel.Email))
            {
                errorMessage.Add("Your email cannot be blank");
            }

            if (!string.IsNullOrEmpty(practitionerUpdateViewModel.PhoneNumber) && !string.IsNullOrWhiteSpace(practitionerUpdateViewModel.PhoneNumber))
            {
                if (!regex.IsMatch(practitionerUpdateViewModel.PhoneNumber))
                {
                    errorMessage.Add("Phone number not valid, please use the following input format: 222-222-2222");
                }
            }
            else
            {
                errorMessage.Add("Phone number cannot be left blank");
            }

            if (practitionerUpdateViewModel.Gender == null)
            {
                errorMessage.Add("You must select a gender");
            }

            if (practitionerUpdateViewModel.CurrentPractitionerTypeId == null || practitionerUpdateViewModel.CurrentPractitionerTypeId == 0)
            {
                errorMessage.Add("You must select a practitioner type");
            }

            if (practitionerUpdateViewModel.CurrentSpokenLanguageIds == null)
            {
                errorMessage.Add("There must be at least one selected spoken language");
            }
            Practitioner practitioner = await _userService.GetPractitionerByEmail(userName);

            List<PractitionerSpokenLanguages> spokenLanguages = await _mediLinkContext.PractitionerSpokenLanguages
                    .Where(psl => psl.PractitionerId == practitioner.Id)
                    .Include(psl => psl.Language)
                    .ToListAsync();

            if (errorMessage.Count == 0)
            {
                if (practitionerUpdateViewModel.CurrentSpokenLanguageIds != null)
                {
                    
                    foreach (var language in spokenLanguages)
                    {
                        _mediLinkContext.PractitionerSpokenLanguages.Remove(language);
                        await _mediLinkContext.SaveChangesAsync();
                    }

                    foreach (var languageId in practitionerUpdateViewModel.CurrentSpokenLanguageIds)
                    {

MediLink/Views/Practitioner/UpdatePractitionerDetails.cshtml
@model PractitionerUpdateViewModel
@{
    ViewData["Title"] = "Update Practition Profile";
}
<nav id="header-st" class="navbar navbar-expand static-top ">
    <div class="mr=auto">
        <a class="navbar-brand mx-0" href="#"><img class="ms-5 me-0" src="~/img/logo2.png" alt="Company Logo" width="70" height="60"></a>
        <h3 id="company-title">MediLink</h3>
    </div>
    <div class="ml-auto mt-4">
        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto ">
                <li class="nav-item">
                    <a class="nav-link mx-2 h6 text-white" href="@Url.Action("PractitionerHomePage", "Practitioner")">Home</a>
                </li>

                <li class="nav-item dropdown no-arrow ">
                    <a class="nav-link dropdown-toggle h6 text-white" href="#" id="reportsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 mx-2 d-none d-lg-inline text-white ">@ViewData["userName"]</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-left shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("ChangePassword", "Practitioner")">
                            <i class="bi bi-people text-gray-400"></i>
                            Change Password
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Logout", "Management")">
                            <i class="bi bi-box-arrow-in-left text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<body class="bg-gradient-login">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-3">
                @if (ViewBag.MyErrorList != null)
                {

                    <div class="alert alert-danger" role="alert">
                        @foreach (var item in ViewBag.MyErrorList)
                        {
                            <span>@item</span>

                            <br>
                        }
                    </div>
                }
                <h4 class="text-center text-black">General Profile Information</h4>
                <form asp-controller="Practitioner" asp-action="UpdatePractitionerDetails" method="post">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="FirstName"class ="control-label">First Name</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="firstName" name="FirstName" value="@Model.FirstName" class="form-control" asp-for="FirstName" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="LastName" class="control-label">Last Name</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="lastname" name="LastName" value="@Model.LastName" class="form-control" asp-for="LastName" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="Email" class="control-label">Email</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="email" name="Email" value="@Model.Email" class="form-control" asp-for="Email" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="phone" name="PhoneNumber" value="@Model.PhoneNumber" placeholder="xxx-xxx-xxxx" class="form-control" asp-for="PhoneNumber" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="IsAcceptingNewPatients" class="control-label">Patient Acceptance Status</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group">
                                        <select name="IsAcceptingNewPatients" class="selectpicker form-control" aria-label="Default select " asp-for="IsAcceptingNewPatients">
                                            <option value="true">Currently Accepting New Patients</option>
                                            <option value="false">Not Currently Accepting New Patients</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="CurrentPractitionerTypeId" class="control-label">Type Of Practitioner</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group">
                                        <select name="CurrentPractitionerTypeId" class="selectpicker form-control" aria-label="Default select " asp-for="CurrentPractitionerTypeId">
                                            @foreach (var type in Model.PractitionerTypes)
                                            {
                                                if(type.Id == Model.CurrentPractitionerTypeId)
                                                {
                                                    <option selected value="@type.Id">@type.Name</option>
                                                }
                                                else
                                                {
                                                    <option value="@type.Id">@type.Name</option>
                                                }
                                                
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label asp-for="Gender" class="control-label">Gender</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group">
                                        <select name="Gender" class="selectpicker form-control" aria-label="Default select " asp-for="Gender">
                                            <option selected disabled value="noselected" )>Select a genre</option>
                                            <option value="Female">Female</option>
                                            <option value="Male">Male</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="inputGroupContainer">
                                <label class="control-label">Spoken Languages</label>
                                <div class="input-group">
                                    <select name="CurrentSpokenLanguageIds" class="selectpicker form-control" aria-label="Default select" asp-for="CurrentSpokenLanguageIds" multiple>
                                        @foreach (var language in Model.Languages)
                                        {
                                            if (Model.CurrentSpokenLanguageIds != null && Model.CurrentSpokenLanguageIds.Contains(language.Id))
                                            {
                                                <option selected value="@language.Id">@language.LanguageName</option>
                                            }
                                            else
                                            {
                                                <option value="@language.Id">@language.LanguageName</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-6 text-center">
                                <a class="btn-user btn-block mt-3 mb-3" href="@Url.Action("PractitionerHomePage", "Practitioner")">Cancel</a>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                    <hr>
                </form>
            </div>
        </div>
    </div>
</body>