MediLink/Entities/WalkInClinic.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MediLink.Entities
{
    public class WalkInClinic
    {
        public int Id { get; set; }

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 100)]
		public string Password { get; set; } = null!;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 100)]
		public string Email { get; set; } = null!;

        public bool IsValidated { get; set; }

        public bool passwordReset { get; set; } = false;

        public string token { get; set; } = string.Empty;

        public bool IsDeleted { get; set; } = false;

		[Column(TypeName = "VARCHAR")]
		[StringLength(maximumLength: 12)]
		public string PhoneNumber { get; set; } = null!;

		public string? ClinicNotes { get; set; }

		public int? CurrentWaitTime { get; set; }

		public int? HistoricalWaitTimeMin { get; set; } //To Be Removed - No longer needed

		public int? HistoricalWaitTimeMax { get; set; } //To Be Removed - No longer needed

        public ICollection<WalkInPractitionerSpokenLanguages> WalkInPractitionerSpokenLanguages { get; set; }

        public ICollection<WalkInClinicHours>? WalkInClinicHours { get; set; }

        public ICollection<WalkInClinicCheckedInPatient>? WalkInClinicCheckedInPatients { get; set; }

        public ICollection<WalkInClinicHistoricalWaitTimes> WalkInClinicHistoricalWaitTimes { get; set; }

        public int OfficeAddressId {  get; set; }

		public OfficeAddress OfficeAddress { get; set; }
    }
}

MediLink/Controllers/WalkInClinicController.cs
using MediLink.Entities;
using MediLink.Models;
using MediLink.Services.Contract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.VisualBasic;
using NuGet.Packaging.Signing;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.Security.Claims;
using System.Text.RegularExpressions;

namespace MediLink.Controllers
{
    public class WalkInClinicController : Controller
    {
        public WalkInClinicController(MediLinkDbContext mediLinkContext, IUserService userService)
        {
            _mediLinkContext = mediLinkContext;
            _userService = userService;
        }

        public async Task<IActionResult> WalkInClinicHomePage()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["userName"] = userName;

            WalkInClinic walkInClinic = await _userService.GetWalkInClinicByEmail(userName);

            OfficeAddress officeAddress = await _mediLinkContext.OfficeAddresses
                .Where(of => of.Id == walkInClinic.OfficeAddressId)
                .FirstOrDefaultAsync();

            List<WalkInPractitionerSpokenLanguages> walkInPractitionerSpokenLanguages = await _mediLinkContext.WalkInPractitionerSpokenLanguages
                .Where(wpsl => wpsl.WalkInPractitionerId == walkInClinic.Id)
                .Include(psl => psl.Language)
                .ToListAsync();

            List<WalkInClinicHours> walkInClinicHours = await _mediLinkContext.WalkInClinicHours
                .Where(wch => wch.WalkInClinicId == walkInClinic.Id)
                .ToListAsync();

            DateTime thirtyMinutesAgo = DateTime.Now.AddMinutes(-30);

            string dayOfTheWeek = DateTime.Now.DayOfWeek.ToString();

            List<WalkInClinicHistoricalWaitTimes> walkInClinicHistoricalWaitTimes = await _mediLinkContext.WalkInClinicHistoricalWaitTimes
                .Where(wch => wch.WalkInClinicId == walkInClinic.Id
                        && wch.DayOfTheWeek == dayOfTheWeek
                        && wch.PatientCheckInTime >= thirtyMinutesAgo) 
                .ToListAsync();
            string currentWaitTimeString = "";

            double currentWaitTime = 0;
            if (walkInClinicHistoricalWaitTimes.Any())
            {
                currentWaitTimeString = ((int)walkInClinicHistoricalWaitTimes.Average(w => w.WaitTimeInSeconds) / 60).ToString() + " minutes";
            }
            else
            {
                currentWaitTimeString = "No Current Data";
            }

            Dictionary<string, string> hoursDictionary = new Dictionary<string, string>();

            foreach (var hours in walkInClinicHours)
            {
                if (hours.OpeningTime == "Closed")
                {
                    hoursDictionary[hours.DayOfTheWeek] = "Closed";
                }
                else
                {
                    hoursDictionary[hours.DayOfTheWeek] = hours.OpeningTime + " - " + hours.ClosingTime;
                }
            }

            WalkClinicViewModel walkClinicViewModel = new WalkClinicViewModel()
            {
                CurrentWaitTime = currentWaitTimeString,
                WalkInClinic = walkInClinic,
                WalkInPractitionerSpokenLanguages = walkInPractitionerSpokenLanguages,
                OfficeAddress = officeAddress,
                WalkInClinicHours = new WalkInClinicHoursInfo()
                {
                    MondayHours = hoursDictionary.GetValueOrDefault("Monday", ""),
                    TuesdayHours = hoursDictionary.GetValueOrDefault("Tuesday", ""),
                    WednesdayHours = hoursDictionary.GetValueOrDefault("Wednesday", ""),
                    ThursdayHours = hoursDictionary.GetValueOrDefault("Thursday", ""),
                    FridayHours = hoursDictionary.GetValueOrDefault("Friday", ""),
                    SaturdayHours = hoursDictionary.GetValueOrDefault("Saturday", ""),
                    SundayHours = hoursDictionary.GetValueOrDefault("Sunday", "")
                }
            };

            if (TempData["WalkInSuccess"] != null)
            {
                ViewBag.WalkInSuccess = TempData["WalkInSuccess"];
            }

            return View(walkClinicViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> UpdateWalkInClinicDetails()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["userName"] = userName;

            WalkInClinic walkInClinic = await _userService.GetWalkInClinicByEmail(userName);

            OfficeAddress officeAddress = await _mediLinkContext.OfficeAddresses
                .Where(of => of.Id == walkInClinic.OfficeAddressId)
                .FirstOrDefaultAsync();

            List<Languages> languages = await _mediLinkContext.Languages.ToListAsync();

            List<WalkInPractitionerSpokenLanguages> walkInPractitionerSpokenLanguages = await _mediLinkContext.WalkInPractitionerSpokenLanguages
                .Where(wpsl => wpsl.WalkInPractitionerId == walkInClinic.Id)
                .ToListAsync();

            List<int> currentSpokenLanguageIds = new List<int>();

            foreach (var language in walkInPractitionerSpokenLanguages)
            {
                currentSpokenLanguageIds.Add(language.LanguageId);
            }

            WalkClinicUpdateViewModel walkClinicUpdateViewModel = new WalkClinicUpdateViewModel()
            {
                Languages = languages,
                CurrentSpokenLanguageIds = currentSpokenLanguageIds,
                PhoneNumber = walkInClinic.PhoneNumber,
                ClinicNotes = walkInClinic.ClinicNotes,
                Email = walkInClinic.Email,
                OfficeName = officeAddress.OfficeName,
                City = officeAddress.City,
                Province = officeAddress.Province,
                Country = officeAddress.country,
                PostalCode = officeAddress.PostalCode,
                StreetAddress = officeAddress.StreetAddress
            };

            return View(walkClinicUpdateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateWalkInClinicDetails(WalkClinicUpdateViewModel walkClinicUpdateViewModel)
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string userName = "";

            if (claimuser.Identity.IsAuthenticated)
            {
                userName = claimuser.Claims.Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();
            }

            List<string> errorMessage = new List<string>();
            string phonePattern = @"^\d{3}-\d{3}-\d{4}$";
            Regex regex = new Regex(phonePattern);

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.Email) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.Email))
            {
                errorMessage.Add("Your email cannot be blank");
            }

            if (!string.IsNullOrEmpty(walkClinicUpdateViewModel.PhoneNumber) && !string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.PhoneNumber))
            {
                if (!regex.IsMatch(walkClinicUpdateViewModel.PhoneNumber))
                {
                    errorMessage.Add("Phone number not valid, please use the following input format: 222-222-2222");
                }
            }
            else
            {
                errorMessage.Add("Phone number cannot be left blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.OfficeName) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.OfficeName))
            {
                errorMessage.Add("Office name cannot be blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.StreetAddress) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.StreetAddress))
            {
                errorMessage.Add("Street address cannot be blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.City) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.City))
            {
                errorMessage.Add("City cannot be blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.PostalCode) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.PostalCode))
            {
                errorMessage.Add("Postal code cannot be blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.Province) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.Province))
            {
                errorMessage.Add("Province cannot be blank");
            }

            if (string.IsNullOrEmpty(walkClinicUpdateViewModel.Country) || string.IsNullOrWhiteSpace(walkClinicUpdateViewModel.Country))
            {
                errorMessage.Add("Country cannot be blank");
            }

            if (walkClinicUpdateViewModel.CurrentSpokenLanguageIds == null)
            {
                errorMessage.Add("There must be at least one selected spoken language");
            }

            WalkInClinic walkInClinic = await _userService.GetWalkInClinicByEmail(userName);

            List<WalkInPractitionerSpokenLanguages> currentSpokenLanguages = await _mediLinkContext.WalkInPractitionerSpokenLanguages

MediLink/Views/WalkInClinic/AddEditOperatingHours.cshtml
@model WalkInHoursViewModel
@{
    ViewData["Title"] = "Add Walk-In Clinic Operating Hours";
}
<nav id="header-st" class="navbar navbar-expand static-top ">
    <div class="mr=auto">
        <a class="navbar-brand mx-0" href="#"><img class="ms-5 me-0" src="~/img/logo2.png" alt="Company Logo" width="70" height="60"></a>
        <h3 id="company-title">MediLink</h3>
    </div>
    <div class="ml-auto mt-4">
        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto ">
                <li class="nav-item dropdown no-arrow ">
                    <a class="nav-link dropdown-toggle h6 text-white" href="#" id="reportsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 mx-2 d-none d-lg-inline text-white ">@ViewData["userName"]</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-left shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Logout", "Management")">
                            <i class="bi bi-box-arrow-in-left text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<body class="bg-gradient-login">
    <div class="container">
        <h4 class="text-center text-black mt-5">Add Your Clinics Operating Hours</h4>
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-3">
                @if (ViewBag.MyErrorList != null)
                {

                    <div class="alert alert-danger" role="alert">
                        @foreach (var item in ViewBag.MyErrorList)
                        {
                            <span>@item</span>

                            <br>
                        }
                    </div>
                }
                <form asp-controller="WalkInClinic" asp-action="AddEditOperatingHours" method="post">
                    <h4>Operating Hours</h4>
                    <p>To indicate that your clinic is closed on a given day, please enter Closed for both the opening and closing hours for that day., </p>
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Mondays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="mondayOpeningTime" name="MondayOpeningTime" value="@Model.MondayOpeningTime" placeholder="00:00" class="form-control" asp-for="MondayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Mondays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="mondayClosingTime" name="MondayClosingTime" value="@Model.MondayClosingTime" placeholder="00:00" class="form-control" asp-for="MondayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Tuesdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="tuesdayOpeningTime" name="TuesdayOpeningTime" value="@Model.TuesdayOpeningTime" placeholder="00:00" class="form-control" asp-for="TuesdayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Tuesdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="tuesdayClosingTime" name="TuesdayClosingTime" value="@Model.TuesdayClosingTime" placeholder="00:00" class="form-control" asp-for="TuesdayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Wednesdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="wednesdayOpeningTime" name="WednesdayOpeningTime" value="@Model.WednesdayOpeningTime" placeholder="00:00" class="form-control" asp-for="WednesdayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Wednesdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="wednesdayClosingTime" name="WednesdayClosingTime" value="@Model.WednesdayClosingTime" placeholder="00:00" class="form-control" asp-for="WednesdayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Thursdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="thursdayOpeningTime" name="ThursdayOpeningTime" value="@Model.ThursdayOpeningTime" placeholder="00:00" class="form-control" asp-for="ThursdayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Thursdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="thursdayClosingTime" name="ThursdayClosingTime" value="@Model.ThursdayClosingTime" placeholder="00:00" class="form-control" asp-for="ThursdayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Fridays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="fridayOpeningTime" name="FridayOpeningTime" value="@Model.FridayOpeningTime" placeholder="00:00" class="form-control" asp-for="FridayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Fridays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="fridayClosingTime" name="FridayClosingTime" value="@Model.FridayClosingTime" placeholder="00:00" class="form-control" asp-for="FridayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Saturdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="saturdayOpeningTime" name="SaturdayOpeningTime" value="@Model.SaturdayOpeningTime" placeholder="00:00" class="form-control" asp-for="SaturdayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Saturdays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="saturdayClosingTime" name="SaturdayClosingTime" value="@Model.SaturdayClosingTime" placeholder="00:00" class="form-control" asp-for="SaturdayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Opening Time On Sundays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="sundayOpeningTime" name="SundayOpeningTime" value="@Model.SundayOpeningTime" placeholder="00:00" class="form-control" asp-for="SundayOpeningTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <label class="control-label">Closing Time On Sundays</label>
                                <div class="inputGroupContainer">
                                    <div class="input-group"><input id="sundayClosingTime" name="SundayClosingTime" value="@Model.SundayClosingTime" placeholder="00:00" class="form-control" asp-for="SundayClosingTime" type="text"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <a class="btn-user btn-block mt-3 mb-3" href="@Url.Action("WalkInClinicHomePage", "WalkInClinic")">Cancel</a>
                        <button type="submit" class="btn btn-primary">Add Operating Hours</button>
                    </div>
                    <hr>
                </form>
            </div>
        </div>
    </div>
</body>

MediLink/Views/WalkInClinic/CheckPatientOut.cshtml
@model CheckOutViewModel
@{
    ViewData["Title"] = "Check Out Patients";
}

<nav id="header-st" class="navbar navbar-expand static-top ">
    <div class="mr=auto">
        <a class="navbar-brand mx-0" href="#"><img class="ms-5 me-0" src="~/img/logo2.png" alt="Company Logo" width="70" height="60"></a>
        <h3 id="company-title">MediLink</h3>
    </div>
    <div class="ml-auto mt-4">
        <div class=" collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto ">
                <li class="nav-item">
                    <a class="nav-link mx-2 h6 text-white" href="@Url.Action("WalkInClinicHomePage", "WalkInClinic")">Home</a>
                </li>

                <li class="nav-item dropdown no-arrow ">
                    <a class="nav-link dropdown-toggle h6 text-white" href="#" id="reportsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 mx-2 d-none d-lg-inline text-white ">@ViewData["userName"]</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-left shadow animated--grow-in"
                         aria-labelledby="userDropdown">
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Logout", "Management")">
                            <i class="bi bi-box-arrow-in-left text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">

    <div class="card">
        <div class="card-header">
            @if (ViewBag.WalkInSuccess != null)
            {
                <div class="alert alert-success" role="alertdialog">
                    <span>@ViewBag.WalkInSuccess</span>
                </div>
            }
            <div class="text-center">
                <h4>Check Patients Out</h4>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                
@*                 <div class="text-left">
                    <a class="btn btn-secondary tex" href="@Url.Action("WalkInClinicHomePage", "WalkInClinic")">Cancel</a>
                </div> *@
            </div>

            <div class="card-body">
                @if (ViewBag.CheckOutSuccess != null)
                {
                    <div class="alert alert-success" role="alertdialog">
                        <span>@ViewBag.CheckOutSuccess</span>
                    </div>
                }

                @if (Model.CheckedInPatients.Count > 0)
                {
                    <table class="table mx-auto">
                        <tr>
                            <th>Patient First Name</th>
                            <th>Patient Last Name</th>
                            <th>Patient Check In Time</th>
                            <th>Actions</th>
                        </tr>
                        @foreach (var patient in Model.CheckedInPatients)
                        {
                            <tr>
                                <td>@patient.PatientFirstName</td>
                                <td>@patient.PatientLastName</td>
                                <td>@patient.PatientCheckInTime.ToString("HH:mm:ss")</td>
                                <td><button type='button' class='btn btn-primary' data-toggle="modal" data-target="#confirmcheckpatientout_@patient.Id" data-id="@patient.Id">Check Patient Out</button></td>
                            </tr>
                        }
                    </table>
                }
                else
                {
                    <p>There are no patients currently checked in</p>
                }

                <div class="text-center mb-4">
                    <a class="btn btn-secondary tex" href="@Url.Action("WalkInClinicHomePage", "WalkInClinic")">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</div>

 @foreach (var patient in Model.CheckedInPatients)
{
    <div class="modal fade" id="confirmcheckpatientout_@patient.Id" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">

                <div class="container">
                    <div class="d-inline text-end">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <h4 id="tiltle-search-pract" class="text-center text-black mt-5">Do you want to check out @patient.PatientFirstName @patient.PatientLastName?</h4>

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="row d-block text-center">
                            <form method="post" asp-controller="WalkInClinic" asp-action="CheckPatientOut">
                                <input type="hidden" name="id" value="@patient.Id" />
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}