MediLink/Controllers/ManagementController.cs
using MediLink.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Web;

using MediLink.Services;
using MediLink.Resources;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using MediLink.Services.Contract;
using MediLink.Models;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using NuGet.Common;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace MediLink.Controllers
{
    public class ManagementController : Controller
    {
        private readonly IUserService _userService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private MediLinkDbContext _mediLinkContext;

        public ManagementController(IUserService userService, IWebHostEnvironment webHostEnvironment, MediLinkDbContext mediLinkDbContext)
        {
            _userService = userService;
            _webHostEnvironment = webHostEnvironment;
            _mediLinkContext = mediLinkDbContext;

        }


        public ActionResult LoginPatient()
        {
            string mensajeResultLog = TempData["mensajeResultLogin"] as string;

            ViewData["mensajeResultLoginPatient"] = mensajeResultLog;

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> LoginPatient(string Email, string Password)
        {
            if (string.IsNullOrEmpty(Email) || string.IsNullOrWhiteSpace(Password))
            {
                ViewData["mensajeResultLoginPatient"] = "Please insert a valid email and password";
                return View();
            }

            Patient patientFound = await _userService.GetUser(Email, Utilities.EncryptPassword(Password));
                      
            if (patientFound == null)
            {
                ViewData["mensajeResultLoginPatient"] = "User Not Found";
                return View();
            }

                       if (!patientFound.IsEmailConfirmed)
            {
                ViewData["mensajeResultLoginPatient"] = "Your email has not been confirmed yet. An email has been sent to your account";
                return View();
            }

            if (patientFound.passwordReset)
            {
                ViewData["mensajeResultLoginPatient"] = "A password reset has been requested for your account and an email has been sent to your account. Please go to the email and reset your password";
                return View();
            }


            List<Claim> claims = new List<Claim>() {
                new Claim(ClaimTypes.Name, patientFound.Email)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                properties
                );

            return RedirectToAction("PatientHomePage", "Patient");
        }

        public ActionResult RegisterPatient()
        {
            PatientNewRequest oPatient = new PatientNewRequest();
            return View(oPatient);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterPatient(PatientNewRequest oPatientNew)
        {
            //verify if the patient already exist 
            Patient patientFound = await _userService.GetUserByEmail(oPatientNew.Email);

            List<string> errorMessage = new List<string>();
            //string[] errorMessage;

            if (patientFound != null)
            {
                errorMessage.Add($"User already exists");

                ViewBag.MyErrorList = errorMessage;
                ViewData["MessageRegister"] = errorMessage;
                return View();
            }


            // Regular expression for phone validation
            string phonePattern = @"^\d{3}-\d{3}-\d{4}$";

            // Creating Regex object
            Regex regex = new Regex(phonePattern);

            DateTime currentDate = DateTime.Now;
            DateTime inputDate = new DateTime(oPatientNew.DoB.Year, oPatientNew.DoB.Month, oPatientNew.DoB.Day);

            // Calculate the current date minus 2 days
            DateTime currentDateMinusTwoDays = currentDate.AddDays(-2);

            if (string.IsNullOrEmpty(oPatientNew.FirstName) || string.IsNullOrWhiteSpace(oPatientNew.FirstName))
            {
                errorMessage.Add("Please enter your first name");
            }

            if (string.IsNullOrEmpty(oPatientNew.LastName) || string.IsNullOrWhiteSpace(oPatientNew.LastName))
            {
                errorMessage.Add("Please enter your last name");
            }

            if (string.IsNullOrEmpty(oPatientNew.Email) || string.IsNullOrWhiteSpace(oPatientNew.Email))
            {
                errorMessage.Add("Please enter you email");
            }

                     

            if (oPatientNew.Password != oPatientNew.ConfirmPassword)
            {
                errorMessage.Add("Password does not match");
                
            }

            if (string.IsNullOrEmpty(oPatientNew.Password) && string.IsNullOrEmpty(oPatientNew.ConfirmPassword))
            {
                errorMessage.Add("Please enter a password");
                
            }

            //verify if the user has selected personal infomation tag
            if (!string.IsNullOrEmpty(oPatientNew.PhoneNumber) || !string.IsNullOrEmpty(oPatientNew.gender) || !oPatientNew.DoB.ToString().Contains("0001-01-01"))
            {
                // Matching the number against the regex pattern
                if (!regex.IsMatch(oPatientNew.PhoneNumber))
                {
                    errorMessage.Add("Phone number not valid, please use the following input format: 222-222-2222");
                  

                }

                // valid if selected a gender
                if (oPatientNew.gender == null)
                {
                    errorMessage.Add("Must select a gender ");
                   

                }

                if (oPatientNew.DoB.ToString().Contains("0001-01-01"))
                {
                    errorMessage.Add("Must select a date of birth");                   

                }
                else
                {
                    if (inputDate >= currentDateMinusTwoDays)
                    {
                        errorMessage.Add("Birthday is invalid, your birthday must be at least two days in the past");
                       

                    }
                }

            }

            //verify if the user has selected address infomation tag
            if (!string.IsNullOrEmpty(oPatientNew.StreetAddress) || !string.IsNullOrEmpty(oPatientNew.City) || !string.IsNullOrEmpty(oPatientNew.PostalCode))
            {
                // valid if selected a address
                if (string.IsNullOrEmpty(oPatientNew.StreetAddress))
                {
                    errorMessage.Add("Please enter your street address ");                    

                }

                // valid if selected a city
                if (string.IsNullOrEmpty(oPatientNew.City))
                {
                    errorMessage.Add("Please enter your city ");
                   
                }

                // valid if selected a city
                if (oPatientNew.Province == null)
                {
                    errorMessage.Add("Please select a province");

                }

                // valid if selected a ;ostcode
                if (string.IsNullOrEmpty(oPatientNew.PostalCode))
                {
                    errorMessage.Add("Please enter your postal code");

                }

            }

            // valid if there are errors
            if (errorMessage.Count == 0)
            {
                oPatientNew.Password = Utilities.EncryptPassword(oPatientNew.Password);

                oPatientNew.token = Utilities.GenerateToken();

                PatientNewRequest userCreated = await _userService.SavePatient(oPatientNew);
                string successMessage = "";
                if (userCreated.Id > 0)
                {
                    // Map the path relative to the content root
                    string path = Path.Combine(_webHostEnvironment.ContentRootPath, "Templates", "ConfirmEmail.html");

                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", HttpContext.Request.Scheme, Request.Headers["host"], "/Management/ConfirmRegisterPatient?token=" + oPatientNew.token);

                    string htmlBody = string.Format(content, oPatientNew.LastName, url);

                    Email emailDTO = new Email()
                    {
                        recipient = oPatientNew.Email,
                        subject = "Confirmation Email MediLink",
                        body = htmlBody
                    };

                    bool sent = EmailService.SendEmail(emailDTO);
                    successMessage = ($"Your account has been created. We have sent a message to the email {oPatientNew.Email} to confirm your email address");

                    ViewBag.PatientRegSuccess = successMessage;
                    ViewData["SuccessMessageRegister"] = successMessage;


                    PatientNewRequest oPatient = new PatientNewRequest();
                    oPatient.FirstName = "";
                    oPatient.LastName = "";
                    oPatient.Password = "";
                    oPatient.ConfirmPassword = "";
                    return View(oPatient);

                }
                else
                {
                    errorMessage.Add("Can not create user");

MediLink/Views/Management/ConfirmRegisterPatient.cshtml
@{
    Layout = null;
}


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediLink Confirm Email</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">  <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/MediLink.styles.css" asp-append-version="true" />

</head>
<body>
    <div class="container mt-3">
        @if ((bool)ViewBag.Response)
        {
            <div class="alert alert-success">
                <p>Your email has been confirmed.</p>
                <a class="btn btn-success" href="@Url.Action("LoginPatient","Management")">Login</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>Error, something went wrong when confirming your email.</p>
            </div>
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
</body>
</html>

MediLink/Views/Management/ConfirmRegisterPractitioner.cshtml
@{
    Layout = null;
}


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediLink Confirm Email</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">  <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/MediLink.styles.css" asp-append-version="true" />

</head>
<body>
    <div class="container mt-3">
        @if ((bool)ViewBag.Response)
        {
            <div class="alert alert-success">
                <p>Your account has been confirmed.</p>
                <a class="btn btn-success" href="@Url.Action("LoginPractitioner","Management")">Login</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>Error, something went wrong when confirming your account.</p>
            </div>
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

MediLink/Views/Management/ConfirmRegisterWalkinClinic.cshtml
@{
    Layout = null;
}


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediLink Confirm Email</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">  <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/MediLink.styles.css" asp-append-version="true" />

</head>
<body>
    <div class="container mt-3">
        @if ((bool)ViewBag.Response)
        {
            <div class="alert alert-success">
                <p>Your account has been confirmed.</p>
                <a class="btn btn-success" href="@Url.Action("LoginWalkinClinic","Management")">Login</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>Error, something went wrong when confirming your account.</p>
            </div>
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

MediLink/Views/Management/LoginPatient.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediLink</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/MediLink.styles.css" asp-append-version="true" />
</head>
<body class="bg-gradient-login">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-lg-block bg-login-image">
                                <div>                                    
                                    <h3 id="company-title-login" class="text-center">Sign In </h3>
                                </div>
                               
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome!!</h1>
                                    </div>
                                    @if (ViewData["mensajeResultLoginPatient"] != null)
                                    {
                                        <div class="alert alert-danger" role="alert">
                                            @ViewData["mensajeResultLoginPatient"]
                                        </div>
                                    }
                                    else if (ViewData["PasswordResetSuccess"] != null)
                                    {
                                        <div class="alert alert-success" role="alert">
                                            @ViewData["PasswordResetSuccess"]
                                        </div>
                                    }
                                    <form class="user" action="@Url.Action("LoginPatient","Management")" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Email Address..." name="Email">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password" name="Password">
                                        </div>

                                        <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                                       
                                        <hr>
                                        
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="btn-user btn-block" href="@Url.Action("Index", "Home")">Return</a>
                                        <button type='button' class="small btn btn-link" data-toggle='modal' data-target='#resetpassword'>Forgot Password?</button>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("RegisterPatient", "Management")">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
    <!-- Modal Reset Password-->
    <div class="modal fade" id="resetpassword" tabindex="-1" aria-labelledby="resetpasswordLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Please insert your email</h1>
                        </div>
                        <form class="w-100" action="@Url.Action("RestartPassword","Management")" method="post">
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user"
                                       id="exampleInputEmail" aria-describedby="emailHelp"
                                       placeholder="your@email.com" name="Email">
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-user btn-block">Reset</button>

                            <hr>

                        </form>
                        
                       
                    </div>




                    

                </div>

            </div>
        </div>
    </div>

    
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>

</html>

MediLink/Views/Management/LoginPractitioner.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediLink</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/MediLink.styles.css" asp-append-version="true" />
</head>
<body class="bg-gradient-login">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-lg-block bg-login-image-doctor">
                                <div>
                                    <h3 id="company-title-login" class="text-center">Sign In </h3>
                                </div>

                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome!!</h1>
                                    </div>
                                    @if (ViewData["mensajeResultLoginPractitioner"] != null)
                                    {
                                        <div class="alert alert-danger" role="alert">
                                            @ViewData["mensajeResultLoginPractitioner"]
                                        </div>
                                    }
                                    <form class="user" action="@Url.Action("LoginPractitioner","Management")" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Email Address..." name="Email">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password" name="Password">
                                        </div>

                                        <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>

                                        <hr>

                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="btn-user btn-block" href="@Url.Action("Index", "Home")">Return</a>
                                        <button type='button' class="small btn btn-link" data-toggle='modal' data-target='#resetpassword'>Forgot Password?</button>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("RegisterPractitioner", "Management")">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
    <!-- Modal Reset Password-->
    <div class="modal fade" id="resetpassword" tabindex="-1" aria-labelledby="resetpasswordLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Please insert your email</h1>
                        </div>
                        <form class="w-100" action="@Url.Action("RestartPasswordPractitioner","Management")" method="post">
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user"
                                       id="exampleInputEmail" aria-describedby="emailHelp"
                                       placeholder="your@email.com" name="Email">
                            </div>

                            <button type="submit" class="btn btn-primary btn-user btn-block">Reset</button>

                            <hr>

                        </form>


                    </div>






                </div>

            </div>
        </div>
    </div>


    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>

</html>